list-calander-boxes=start
Zebreu/binbinneverforgets pull request #8
Opened 2020-12-30 20:08 UTC by JonathanCote90

2020-12-30 20:10 UTC, Gownsan approved these changes

2020-12-30 22:52 UTC, Zebreu approved these changes

2021-01-15 01:18 UTC, breault-vincent requested changes

2021-01-15 01:18 UTC, breault-vincent commented on simpleone/src/simpletemplate/Dashboard.js
> -                      Dans ta face, Gih.
I think this removal will break core functionality. Can't pass the merge request until fixed.

2021-01-18 00:40 UTC, merged